### ISSUE TITLE
v2.8.0 is not published to https://plugins.gradle.org/m2

### ISSUE THREAD

**Issue by yizhuan** [AOEpeople/gradle-jenkins-job-dsl-plugin#15]
The code and README are all changed to 2.8.0 and 
I check https://plugins.gradle.org/m2/com/aoe/jenkins-job-dsl/com.aoe.jenkins-job-dsl.gradle.plugin/
The last version is still 2.4.0.

**Comment by carstenlenz** [comment]
I'm sorry. It can take up to 24h for a plugin to be checked and published by the Gradle Plugin Portal. So I am afraid I must ask for a little patience and checking again maybe tomorrow.

**Comment by yizhuan** [comment]
Thanks @carstenlenz for the update! 25 ,26,27 are all not in the repo, I thought it might be an error. Will check the repo for 2.8.0 then

**Comment by yizhuan** [comment]
@carstenlenz, v2.8.0 is still NOT in the repository.

**Comment by carstenlenz** [comment]
Thanks for you update :( 
I raised an issue in the Gradle forum about the delay. Sorry for any inconveniences caused.

**Comment by carstenlenz** [comment]
The issue did help. Version 2.8.0 is now published 
https://plugins.gradle.org/plugin/com.aoe.jenkins-job-dsl/2.8.0
